# Makefile

run-dev:
	if exist dev.env (copy dev.env .env)
	set PYTHONPATH=%cd% && poetry run python src\main.py


build:
	docker build -t trade_producer -f D:\Crypto-Price-Predictor\services\trade_producer\Dockerfile .

run: build
	docker run ^
		--network=redpanda_network ^
		--env-file prod.env ^
		trade_producer
